### ISSUE TITLE
Error Audio in Google Emulator in Firefox Browser

### ISSUE THREAD

**Issue by roxanneen** [appetizeio/appetize-docs-gitbook#1]
Ran Appetize to test a couple of publicly available Google Apps, but noticed in both cases (an audio-only game app and in a youtube alternative - NewPipe) that audio doesn't work in the emulator. 
The app loads fine, I can sign up, create accounts, download, save, search, use other apps etc. 
When I play a video, for example, it will play video contents, but not audio. 
If I play an audio stream, sound is dead. 
Any way to fix this so it works with browsers like Firefox?

**Comment by snyderj** [comment]
Hi @roxananasoi - unfortunately, we do not currently support audio in Appetize.io. We will make an announcement via Twitter if we do add support for audio in the future. Thanks!
